// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum NativeAppearancePigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Generated class from Pigeon that represents data sent in messages.
struct NativeStyleData: Hashable, CustomStringConvertible {
  var background: Int64? = nil
  var headline: Int64? = nil
  var body: Int64? = nil
  var callToActionBackground: Int64? = nil
  var callToActionText: Int64? = nil
  var callToActionCornerRadius: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeStyleData? {
    let background: Int64? = nilOrValue(pigeonVar_list[0])
    let headline: Int64? = nilOrValue(pigeonVar_list[1])
    let body: Int64? = nilOrValue(pigeonVar_list[2])
    let callToActionBackground: Int64? = nilOrValue(pigeonVar_list[3])
    let callToActionText: Int64? = nilOrValue(pigeonVar_list[4])
    let callToActionCornerRadius: Double? = nilOrValue(pigeonVar_list[5])

    return NativeStyleData(
      background: background,
      headline: headline,
      body: body,
      callToActionBackground: callToActionBackground,
      callToActionText: callToActionText,
      callToActionCornerRadius: callToActionCornerRadius
    )
  }
  func toList() -> [Any?] {
    return [
      background,
      headline,
      body,
      callToActionBackground,
      callToActionText,
      callToActionCornerRadius,
    ]
  }
  static func == (lhs: NativeStyleData, rhs: NativeStyleData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return NativeAppearancePigeonInternal.deepEquals(lhs.background, rhs.background) && NativeAppearancePigeonInternal.deepEquals(lhs.headline, rhs.headline) && NativeAppearancePigeonInternal.deepEquals(lhs.body, rhs.body) && NativeAppearancePigeonInternal.deepEquals(lhs.callToActionBackground, rhs.callToActionBackground) && NativeAppearancePigeonInternal.deepEquals(lhs.callToActionText, rhs.callToActionText) && NativeAppearancePigeonInternal.deepEquals(lhs.callToActionCornerRadius, rhs.callToActionCornerRadius)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeStyleData")
    NativeAppearancePigeonInternal.deepHash(value: background, hasher: &hasher)
    NativeAppearancePigeonInternal.deepHash(value: headline, hasher: &hasher)
    NativeAppearancePigeonInternal.deepHash(value: body, hasher: &hasher)
    NativeAppearancePigeonInternal.deepHash(value: callToActionBackground, hasher: &hasher)
    NativeAppearancePigeonInternal.deepHash(value: callToActionText, hasher: &hasher)
    NativeAppearancePigeonInternal.deepHash(value: callToActionCornerRadius, hasher: &hasher)
  }

  public var description: String {
    return "NativeStyleData(background: \(String(describing: background)), headline: \(String(describing: headline)), body: \(String(describing: body)), callToActionBackground: \(String(describing: callToActionBackground)), callToActionText: \(String(describing: callToActionText)), callToActionCornerRadius: \(String(describing: callToActionCornerRadius)))"
  }
}

/// Actual host width and scaled typography. Null height requests inline sizing.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativeLayoutRequest: Hashable, CustomStringConvertible {
  var width: Double
  var height: Double? = nil
  var headlineSize: Double
  var bodySize: Double
  var metadataSize: Double
  var actionSize: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeLayoutRequest? {
    let width = pigeonVar_list[0] as! Double
    let height: Double? = nilOrValue(pigeonVar_list[1])
    let headlineSize = pigeonVar_list[2] as! Double
    let bodySize = pigeonVar_list[3] as! Double
    let metadataSize = pigeonVar_list[4] as! Double
    let actionSize = pigeonVar_list[5] as! Double

    return NativeLayoutRequest(
      width: width,
      height: height,
      headlineSize: headlineSize,
      bodySize: bodySize,
      metadataSize: metadataSize,
      actionSize: actionSize
    )
  }
  func toList() -> [Any?] {
    return [
      width,
      height,
      headlineSize,
      bodySize,
      metadataSize,
      actionSize,
    ]
  }
  static func == (lhs: NativeLayoutRequest, rhs: NativeLayoutRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return NativeAppearancePigeonInternal.deepEquals(lhs.width, rhs.width) && NativeAppearancePigeonInternal.deepEquals(lhs.height, rhs.height) && NativeAppearancePigeonInternal.deepEquals(lhs.headlineSize, rhs.headlineSize) && NativeAppearancePigeonInternal.deepEquals(lhs.bodySize, rhs.bodySize) && NativeAppearancePigeonInternal.deepEquals(lhs.metadataSize, rhs.metadataSize) && NativeAppearancePigeonInternal.deepEquals(lhs.actionSize, rhs.actionSize)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeLayoutRequest")
    NativeAppearancePigeonInternal.deepHash(value: width, hasher: &hasher)
    NativeAppearancePigeonInternal.deepHash(value: height, hasher: &hasher)
    NativeAppearancePigeonInternal.deepHash(value: headlineSize, hasher: &hasher)
    NativeAppearancePigeonInternal.deepHash(value: bodySize, hasher: &hasher)
    NativeAppearancePigeonInternal.deepHash(value: metadataSize, hasher: &hasher)
    NativeAppearancePigeonInternal.deepHash(value: actionSize, hasher: &hasher)
  }

  public var description: String {
    return "NativeLayoutRequest(width: \(String(describing: width)), height: \(String(describing: height)), headlineSize: \(String(describing: headlineSize)), bodySize: \(String(describing: bodySize)), metadataSize: \(String(describing: metadataSize)), actionSize: \(String(describing: actionSize)))"
  }
}

private class NativeAppearancePigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return NativeStyleData.fromList(self.readValue() as! [Any?])
    case 130:
      return NativeLayoutRequest.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class NativeAppearancePigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? NativeStyleData {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? NativeLayoutRequest {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class NativeAppearancePigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return NativeAppearancePigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return NativeAppearancePigeonCodecWriter(data: data)
  }
}

class NativeAppearancePigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = NativeAppearancePigeonCodec(readerWriter: NativeAppearancePigeonCodecReaderWriter())
}

/// Complete render manifest, not a delta: omitted renders are released.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol NativeAppearanceHost {
  func startSession(sessionId: String) throws
  func applyStyle(sessionId: String, revision: Int64, renders: [String: NativeStyleData]) throws
  func endSession(sessionId: String) throws
  func layoutNativeAd(sessionId: String, renderId: String, request: NativeLayoutRequest) throws -> Double
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class NativeAppearanceHostSetup {
  static var codec: FlutterStandardMessageCodec { NativeAppearancePigeonCodec.shared }
  /// Sets up an instance of `NativeAppearanceHost` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: NativeAppearanceHost?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let startSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.admob_kit_flutter.NativeAppearanceHost.startSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! String
        do {
          try api.startSession(sessionId: sessionIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startSessionChannel.setMessageHandler(nil)
    }
    let applyStyleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.admob_kit_flutter.NativeAppearanceHost.applyStyle\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      applyStyleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! String
        let revisionArg = args[1] as! Int64
        let rendersArg = args[2] as! [String: NativeStyleData]
        do {
          try api.applyStyle(sessionId: sessionIdArg, revision: revisionArg, renders: rendersArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      applyStyleChannel.setMessageHandler(nil)
    }
    let endSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.admob_kit_flutter.NativeAppearanceHost.endSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      endSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! String
        do {
          try api.endSession(sessionId: sessionIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      endSessionChannel.setMessageHandler(nil)
    }
    let layoutNativeAdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.admob_kit_flutter.NativeAppearanceHost.layoutNativeAd\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      layoutNativeAdChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! String
        let renderIdArg = args[1] as! String
        let requestArg = args[2] as! NativeLayoutRequest
        do {
          let result = try api.layoutNativeAd(sessionId: sessionIdArg, renderId: renderIdArg, request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      layoutNativeAdChannel.setMessageHandler(nil)
    }
  }
}
