// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.example.flutter_ads

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object NativeAppearancePigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeStyleData (
  val background: Long? = null,
  val headline: Long? = null,
  val body: Long? = null,
  val callToActionBackground: Long? = null,
  val callToActionText: Long? = null,
  val callToActionCornerRadius: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeStyleData {
      val background = pigeonVar_list[0] as Long?
      val headline = pigeonVar_list[1] as Long?
      val body = pigeonVar_list[2] as Long?
      val callToActionBackground = pigeonVar_list[3] as Long?
      val callToActionText = pigeonVar_list[4] as Long?
      val callToActionCornerRadius = pigeonVar_list[5] as Double?
      return NativeStyleData(background, headline, body, callToActionBackground, callToActionText, callToActionCornerRadius)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      background,
      headline,
      body,
      callToActionBackground,
      callToActionText,
      callToActionCornerRadius,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeStyleData
    return NativeAppearancePigeonUtils.deepEquals(this.background, other.background) && NativeAppearancePigeonUtils.deepEquals(this.headline, other.headline) && NativeAppearancePigeonUtils.deepEquals(this.body, other.body) && NativeAppearancePigeonUtils.deepEquals(this.callToActionBackground, other.callToActionBackground) && NativeAppearancePigeonUtils.deepEquals(this.callToActionText, other.callToActionText) && NativeAppearancePigeonUtils.deepEquals(this.callToActionCornerRadius, other.callToActionCornerRadius)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NativeAppearancePigeonUtils.deepHash(this.background)
    result = 31 * result + NativeAppearancePigeonUtils.deepHash(this.headline)
    result = 31 * result + NativeAppearancePigeonUtils.deepHash(this.body)
    result = 31 * result + NativeAppearancePigeonUtils.deepHash(this.callToActionBackground)
    result = 31 * result + NativeAppearancePigeonUtils.deepHash(this.callToActionText)
    result = 31 * result + NativeAppearancePigeonUtils.deepHash(this.callToActionCornerRadius)
    return result
  }
  override fun toString(): String {
    return "NativeStyleData(background=$background, headline=$headline, body=$body, callToActionBackground=$callToActionBackground, callToActionText=$callToActionText, callToActionCornerRadius=$callToActionCornerRadius)"
  }
}

/**
 * Actual host width and scaled typography. Null height requests inline sizing.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NativeLayoutRequest (
  val width: Double,
  val height: Double? = null,
  val headlineSize: Double,
  val bodySize: Double,
  val metadataSize: Double,
  val actionSize: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeLayoutRequest {
      val width = pigeonVar_list[0] as Double
      val height = pigeonVar_list[1] as Double?
      val headlineSize = pigeonVar_list[2] as Double
      val bodySize = pigeonVar_list[3] as Double
      val metadataSize = pigeonVar_list[4] as Double
      val actionSize = pigeonVar_list[5] as Double
      return NativeLayoutRequest(width, height, headlineSize, bodySize, metadataSize, actionSize)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      width,
      height,
      headlineSize,
      bodySize,
      metadataSize,
      actionSize,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeLayoutRequest
    return NativeAppearancePigeonUtils.deepEquals(this.width, other.width) && NativeAppearancePigeonUtils.deepEquals(this.height, other.height) && NativeAppearancePigeonUtils.deepEquals(this.headlineSize, other.headlineSize) && NativeAppearancePigeonUtils.deepEquals(this.bodySize, other.bodySize) && NativeAppearancePigeonUtils.deepEquals(this.metadataSize, other.metadataSize) && NativeAppearancePigeonUtils.deepEquals(this.actionSize, other.actionSize)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NativeAppearancePigeonUtils.deepHash(this.width)
    result = 31 * result + NativeAppearancePigeonUtils.deepHash(this.height)
    result = 31 * result + NativeAppearancePigeonUtils.deepHash(this.headlineSize)
    result = 31 * result + NativeAppearancePigeonUtils.deepHash(this.bodySize)
    result = 31 * result + NativeAppearancePigeonUtils.deepHash(this.metadataSize)
    result = 31 * result + NativeAppearancePigeonUtils.deepHash(this.actionSize)
    return result
  }
  override fun toString(): String {
    return "NativeLayoutRequest(width=$width, height=$height, headlineSize=$headlineSize, bodySize=$bodySize, metadataSize=$metadataSize, actionSize=$actionSize)"
  }
}
private open class NativeAppearancePigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeStyleData.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeLayoutRequest.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NativeStyleData -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is NativeLayoutRequest -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * Complete render manifest, not a delta: omitted renders are released.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface NativeAppearanceHost {
  fun startSession(sessionId: String)
  fun applyStyle(sessionId: String, revision: Long, renders: Map<String, NativeStyleData>)
  fun endSession(sessionId: String)
  fun layoutNativeAd(sessionId: String, renderId: String, request: NativeLayoutRequest): Double

  companion object {
    /** The codec used by NativeAppearanceHost. */
    val codec: MessageCodec<Any?> by lazy {
      NativeAppearancePigeonCodec()
    }
    /** Sets up an instance of `NativeAppearanceHost` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NativeAppearanceHost?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.admob_kit_flutter.NativeAppearanceHost.startSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.startSession(sessionIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              NativeAppearancePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.admob_kit_flutter.NativeAppearanceHost.applyStyle$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            val revisionArg = args[1] as Long
            val rendersArg = args[2] as Map<String, NativeStyleData>
            val wrapped: List<Any?> = try {
              api.applyStyle(sessionIdArg, revisionArg, rendersArg)
              listOf(null)
            } catch (exception: Throwable) {
              NativeAppearancePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.admob_kit_flutter.NativeAppearanceHost.endSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.endSession(sessionIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              NativeAppearancePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.admob_kit_flutter.NativeAppearanceHost.layoutNativeAd$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            val renderIdArg = args[1] as String
            val requestArg = args[2] as NativeLayoutRequest
            val wrapped: List<Any?> = try {
              listOf(api.layoutNativeAd(sessionIdArg, renderIdArg, requestArg))
            } catch (exception: Throwable) {
              NativeAppearancePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
